services:
    _defaults:
        autowire: true
        autoconfigure: true
    # Chargement des services
    ICS\SearchBundle\Controller\:
        resource: "../src/Controller"
        tags: ['controller.services_arguments']
    ICS\SearchBundle\Service\:
        resource: "../src/Service"
        tags: ['controller.services_arguments']
    ICS\SearchBundle\Command\:
        resource: "../src/Command"
        tags: ['controller.services_arguments']
    ICS\SearchBundle\Twig\:
        resource: "../src/Twig"
        tags: ['controller.services_arguments']
    ICS\SearchBundle\Form\:
        resource: "../src/Form"
        tags: ['controller.services_arguments']
